### ISSUE TITLE
ImportError: cannot import name _args_from_interpreter_flags

### ISSUE THREAD

**Issue by xiaohan2012** [uqfoundation/multiprocess#11] opened 2015-12-30 18:15 UTC
```
In [2]: import multiprocess as mp
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
/cs/work/home/hxiao/code/lst/<ipython-input-2-e802685ea588> in <module>()
----> 1 import multiprocess as mp

/cs/home/hxiao/.local/lib/python2.7/site-packages/multiprocess/__init__.py in <module>()
     63
     64 from multiprocess.process import Process, current_process, active_children
---> 65 from multiprocess.util import SUBDEBUG, SUBWARNING
     66
     67 #


/cs/home/hxiao/.local/lib/python2.7/site-packages/multiprocess/util.py in <module>()
     39 import threading        # we want threading to install it's
     40                         # cleanup function before multiprocessing does

---> 41 from subprocess import _args_from_interpreter_flags
     42
     43 from multiprocess.process import current_process, active_children

ImportError: cannot import name _args_from_interpreter_flags

```

Python version:

```
Python 2.7.3 (default, Jun 22 2015, 19:33:41)
[GCC 4.6.3] on linux2
```

**Comment by xiaohan2012** [comment] 2015-12-30 18:19
However, if I remove the line as I found it's not called in the `multiprocess/util.py`
` from subprocess import _args_from_interpreter_flags`

It will work.

**Comment by mmckerns** [comment] 2015-12-31 13:04
That line is needed for when python is compiled without threading, but does not do much otherwise, so it's probably OK to do that.  I would expect you are seeing an error because the `multiprocess` code is a fork of `python 2.7.10` and you are using `python 2.7.3`.  Typically, there's not an issue unless there was a bug in the previous version of python that is being exposed, or there was a backward incompatible change,  I'd recommend upgrading your python (to `python 2.7.11`).  I'm going to close this, but please feel free to reopen/comment here if your issue is not resolved.

**Closed by mmckerns** 2015-12-31 13:04 UTC
Labels: voided

**Comment by julianofoleiss** [comment] 2016-05-17 12:40
For some reason I'm still getting this. Using multiprocess 0.70.4...

I'm also using this inside a virtual environment. Not sure if it's ok.

Thanks.

```
Traceback (most recent call last):
  File "fetc.py", line 6, in <module>
    from feature_extraction import FeatureExtractor
  File "/home-local/juliano/acf/pymir3/scripts/acf/feature_extraction.py", line 5, in <module>
    from multiprocess import Pool
  File "/home-local/juliano/dcase2016/dcase2016/venv/local/lib/python2.7/site-packages/multiprocess/__init__.py", line 65, in <module>
    from multiprocess.util import SUBDEBUG, SUBWARNING
  File "/home-local/juliano/dcase2016/dcase2016/venv/local/lib/python2.7/site-packages/multiprocess/util.py", line 41, in <module>
    from subprocess import _args_from_interpreter_flags
ImportError: cannot import name _args_from_interpreter_flags
Traceback (most recent call last):
  File "fetc.py", line 6, in <module>
    from feature_extraction import FeatureExtractor
  File "/home-local/juliano/acf/pymir3/scripts/acf/feature_extraction.py", line 5, in <module>
    from multiprocess import Pool
  File "/home-local/juliano/dcase2016/dcase2016/venv/local/lib/python2.7/site-packages/multiprocess/__init__.py", line 65, in <module>
    from multiprocess.util import SUBDEBUG, SUBWARNING
  File "/home-local/juliano/dcase2016/dcase2016/venv/local/lib/python2.7/site-packages/multiprocess/util.py", line 41, in <module>
    from subprocess import _args_from_interpreter_flags
ImportError: cannot import name _args_from_interpreter_flags
```

**Comment by mmckerns** [comment] 2016-05-18 13:31
@julianofoleiss: What's your minor version of python 2.7?  Most likely this is because `multiprocess` is a fork of the latest version of `multiprocessing`… and if you have an old enough version of 2.7, you could see inconsistencies in packages (such as the one above).

**Comment by mmckerns** [comment] 2016-05-18 13:35
I guess if removing the line as @xiaohan2012 has done above has no impact on `multiprocess`, then I could pretty easily put a `try`/ `except` statement around the import.  So, if you don't want to upgrade your python, and you'd rather make the edit as above, could you also confirm the workaround is ok?

**Comment by julianofoleiss** [comment] 2016-05-18 13:43
Hi!

python --version returns `Python 2.7.3`. The multiprocessing library is in version 2.6.2.1.

I can confirm that @xiaohan2012 's workaround works.

Thanks!

**Comment by mmckerns** [comment] 2016-06-02 16:44
added workaround in d344cf69ce62b5e465cf90a8f565c274783ae59e
