### ISSUE TITLE
replacing dill with cloudpickle ?

### ISSUE THREAD

**Issue by stonebig** [uqfoundation/multiprocess#22] opened 2016-08-28 09:04 UTC
On windows dill is a problem.

Would it be easy to replace it with cloudpickle, as did the "dask" package ?
https://github.com/dask/dask/pull/865

**Comment by mmckerns** [comment] 2016-08-29 13:15
In terms of object serialization, I believe that `dill` is more robust than `cloudpickle` against the set of standard python objects -- however `cloudpickle` can handle some cases that `dill` does not, or at least the default `dill.settings` do not.  The typical thing that is done in cases like this is to abstract the serializer, which could be done with little problem.  This has been the practice of `IPython` (in `parallel`), `mpi4py`, and other packages.

So unless you are referencing the issue that `dill` uses `pyreadline` (https://github.com/uqfoundation/dill/issues/171), the answer I believe is yes, it should be somewhat easy.  If you are referencing the `pyreadline` issue, then that's a `dill` issue, and probably even easier as `multiprocess` would not need to change at all.

**Comment by mmckerns** [comment] 2018-06-22 03:29
this is essentially a duplicate of #5.  Closing... but will focus on `cloudpickle` as the alternate serializer.

**Closed by mmckerns** 2018-06-22 03:29 UTC
Labels: duplicate
