### ISSUE TITLE
importing multiprocess from R using reticulate fails

### ISSUE THREAD

**Issue by jacob7182** [uqfoundation/multiprocess#43] opened 2018-06-20 10:47 UTC
My program seems to not proceed further beyond the `docs = poolObj.map(nlp,textStr)` statement. I am using python 3.6 on windows server, 64 bit virtual machine with 8 virtual CPU's. Its on Azure Cloud.

I installed tcc and put it under C:/Apps/tcc and added it to to the system path. Downloaded the multiprocess source from GitHub, build and installed it.
I am able to call `import _multiprocess`
 
My code is as below

```
import spacy
import pandas as pd
import numpy as np
from multiprocess import Pool
from multiprocess import freeze_support as freezeSupport

def getEntitiesByChunk(textList):   
    
    path="C:/Apps/Anaconda3/model"
    nlp= spacy.load(path,disable=['tokenizer','parser', 'textcat','tagger']) 
    textList = np.array(textList)
    if(len(textList)<400):
        n=2
    else:    
        n=int(len(textList)/400)
    textChunks = np.array_split(textList,n)
    textStr = [(' ').join(textChunks[i].tolist()) for i in range(n)]
    
    entitiesfinal=[]
    entities = []
   
    freezeSupport()
    poolObj = Pool(5)
    
    docs = poolObj.map(nlp,textStr)
    for doc in docs: 
	entities =[{'text':ent.text,'type': ent.label_} for ent in doc.ents] 
        entitiesfinal.extend(entities)	

    return pd.DataFrame(df) 
```

**Comment by jacob7182** [comment] 2018-06-20 17:51
An additional info, this python module is being called from an R shiny program.  Is the python module containing multiprocess not being called from `if __name__ == '__main__'`  could be the issue?

**Comment by jacob7182** [comment] 2018-06-21 03:50
Here is a simple program which can replicate the issue.  I think the issue is occurring due multiprocessing being done in Python and being called from R shiny.  
R program  (App.R)
`library(shiny)
library(reticulate)
ui <- fluidPage(
      titlePanel("Sample Program"),      
      mainPanel(
         uiOutput("txtValue")
      )   
)
server <- function(input, output) {   
   output$txtValue <- renderUI({      
     x    <- py_run_file("../../PythonCode/Multiprocessing/mainf.py") 
     print(x$m)      
   })
}
shinyApp(ui = ui, server = server)`

Python Program (mainf.py)
`from multiprocess import Pool
from multiprocess import freeze_support as freezeSupport
    
def f(x):
    return x**2

def f2():
    p = Pool(5)
    y = p.map(f, [1,2,3,4,5])
    return y

if __name__ == '__main__': 
    freezeSupport()
    m=f2()`

**Comment by mmckerns** [comment] 2019-05-02 05:12
I built your python script, and the python code works just fine when run by itself (i.e. `python main.py` from the terminal).  Then I tried to run it from `R` with `reticulate`.  It failed, with this error...

```
> library('reticulate')
> x <- py_run_file('mainf.py')
Error in py_run_file_impl(file, local, convert) : 
  SyntaxError: invalid syntax (context.py, line 131)

Detailed traceback: 
  File "<string>", line 1, in <module>
  File "/Users/mmckerns/lib/python3.6/site-packages/multiprocess-0.70.8.dev0-py3.6-macosx-10.12-x86_64.egg/multiprocess/__init__.py", line 16, in <module>
    from . import context
> 
```
It seems to just fail on the import of `multiprocess.context`.  So, I tried replacing `multiprocess` with `multiprocessing` (from STL python), and it worked.

```
> library('reticulate')
> x <- py_run_file('mainf.py')
> print(x$m)
[1]  1  4  9 16 25
> 
```

So, if I edit the test code to just be this:
```
if __name__ == '__main__':
    import multiprocess as mp
```
it also fails on the import when called from `R`.

However... you'll note that I was running python 3.6.  When I switch to python 2.7, it works... and your original code (using `multiprocess`) also works.

Upon further investigation, if I run using any version of python 3, it fails when using `multiprocess`.  Looks like a workaround would be to use `multiprocessing` not `multiprocess`.  I'm not sure what the issue is, as it's basically failing right out of the gun, on the import of `multiprocess`.

This will need further investigation.

**Comment by mmckerns** [comment] 2019-05-02 05:25
Even simpler test case..
```
> library('reticulate')
> mp <- import('multiprocessing')
> mp <- import('multiprocess')
Error in py_module_import(module, convert = convert) : 
  SyntaxError: invalid syntax (context.py, line 131)

Detailed traceback: 
  File "/Users/mmckerns/lib/python3.6/site-packages/multiprocess-0.70.8.dev0-py3.6-macosx-10.12-x86_64.egg/multiprocess/__init__.py", line 16, in <module>
    from . import context
> 
```

**Comment by mmckerns** [comment] 2019-05-02 05:35
There are plans to update the `multiprocess` fork to more recent versions of `multiprocessing` (see #51).  I'm wondering if that will have any effect.

I've also found this issue... https://github.com/rstudio/reticulate/issues/98, which seems to be a good place to start.

**Comment by mmckerns** [comment] 2023-01-30 17:14
Closing this out. Apparently, by keeping `multiprocess` in sync with the latest version of `multiprocessing`, this issue doesn't occur.

**Closed by mmckerns** 2023-01-30 17:14 UTC
Labels: compatibility
