### ISSUE TITLE
ModuleNotFoundError: No module named 'multiprocess'

### ISSUE THREAD

**Issue by Nitrooo** [uqfoundation/multiprocess#61] opened 2019-06-29 13:03 UTC
(This is actually an issue related to pathos, but I can't delete it and move to pathos' page)

I installed pathos on my Windows machine, Python 3.7.3:

```
(venv) D:\Projects\Python\Test\venv>pip install pathos
Collecting pathos
  Using cached https://files.pythonhosted.org/packages/ed/6f/c6d34bda9f6383b693418f7b2340e8e6692e5a0ed154e918c09399fbf2ec/pathos-0.2.4.tar.gz
Collecting ppft>=1.6.6.1 (from pathos)
  Using cached https://files.pythonhosted.org/packages/5b/16/9e83c2aa45949ee9cd6e8731275acdaeb6c624b8728d6598196c65074f3e/ppft-1.6.6.1.tar.gz
Collecting dill>=0.3.0 (from pathos)
  Using cached https://files.pythonhosted.org/packages/39/7a/70803635c850e351257029089d38748516a280864c97cbc73087afef6d51/dill-0.3.0.tar.gz
Collecting pox>=0.2.6 (from pathos)
  Using cached https://files.pythonhosted.org/packages/b0/8e/e8095866c3b512f9ef844ad20669e0c4785da1784dcfd282377896ffd3b1/pox-0.2.6.tar.gz
Collecting multiprocess>=0.70.8 (from pathos)
  Using cached https://files.pythonhosted.org/packages/8f/1c/60b2259979898b93693fbc7ffcbe57dc4339fc609d58e11bf19083aee155/multiprocess-0.70.8-cp37-cp37m-win_amd64.whl
Requirement already satisfied: six>=1.7.3 in d:\projects\python\snakeai\venv_test\lib\site-packages (from ppft>=1.6.6.1->pathos) (1.12.0)
Installing collected packages: ppft, dill, pox, multiprocess, pathos
  Running setup.py install for ppft ... done
  Running setup.py install for dill ... done
  Running setup.py install for pox ... done
  Running setup.py install for pathos ... done
Successfully installed dill-0.3.0 multiprocess-0.70.8 pathos-0.2.4 pox-0.2.6 ppft-1.6.6.1
```

When I run `p = ProcessPool(nodes=4)` I get:
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'multiprocess'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'multiprocess'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'multiprocess'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'multiprocess'
```

`multiprocess` is installed by wheel, so I shouldn't even need a C compiler, if I got it right.
This is the output of Python console:
```
>>> import multiprocess
>>> print(multiprocess)
<module 'multiprocess' from 'D:\\Projects\\Python\\Test\\venv\\lib\\site-packages\\multiprocess\\__init__.py'>
```
I found several issues related to this error but they didn't help.

**Comment by Nitrooo** [comment] 2019-06-29 14:46
This is the code that raises the errors:

```
import os
from pathos.multiprocessing import ProcessPool


def square(n):
    print("Worker process id for {0}: {1}".format(n, os.getpid()))
    return n * n


if __name__ == "__main__":
    mylist = [1, 2, 3, 4, 5]
    p = ProcessPool()
    result = p.map(square, mylist)

    print(result)

```

The errors are raised in `popen_spawn_win32.py` at:

```
        with open(wfd, 'wb', closefd=True) as to_child:
            # start process
            try:
                hp, ht, pid, tid = _winapi.CreateProcess(
                    python_exe, cmd,
                    env, None, False, 0, None, None, None)
                _winapi.CloseHandle(ht)
            except:
                _winapi.CloseHandle(rhandle)
                raise
```

In my case `python_exe` points to the base exe of the interpreter since the condition after the `bpo-35797` comment is met, as I run the program inside a venv.
I'm not sure what's going on, but CreateProcess fails with the error I pasted above.
If I substitute `python_exe` with `sys.executable` (pointing to the venv executable) or just set `WINENV` to `False`, the process is created and no errors are raised, but the program gives no output and hangs forever.

**Comment by mmckerns** [comment] 2019-06-29 16:32
Correct, if you use the wheel, you shouldn't need a C compiler.

What's your version of python?  I can't tell from the above.  That will help me test against your code.
Most of the python versions are fairly extensively tested on Windows -- however I just built the code for 3.8beta1, and there may be kinks to work out.

Also, does this work?
```
import os
from multiprocess import Pool


def square(n):
    print("Worker process id for {0}: {1}".format(n, os.getpid()))
    return n * n


if __name__ == "__main__":
    mylist = [1, 2, 3, 4, 5]
    p = Pool()
    print("pool created")
    result = p.map(square, mylist)
    print(result)
```

**Comment by mmckerns** [comment] 2019-06-29 16:32
Could you also paste in the traceback.  That's usually helpful.

**Comment by Nitrooo** [comment] 2019-06-29 17:35
> ```
> import os
> from multiprocess import Pool
> 
> 
> def square(n):
>     print("Worker process id for {0}: {1}".format(n, os.getpid()))
>     return n * n
> 
> 
> if __name__ == "__main__":
>     mylist = [1, 2, 3, 4, 5]
>     p = Pool()
>     print("pool created")
>     result = p.map(square, mylist)
>     print(result)
> ```

Your code above behaves just like mine. There's no traceback, all I get is an infinite print of:
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'multiprocess'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'multiprocess'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'multiprocess'
.
.
.
```

**Comment by Nitrooo** [comment] 2019-06-29 18:02
Actually "pool created" is printed, despite the errors:

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'multiprocess'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'multiprocess'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'multiprocess'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'multiprocess'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'multiprocess'
pool created  <-------------------------------------------------------- print is called
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'multiprocess'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'multiprocess'
```
If I just run the script it keeps printing errors forever, if I put a breakpoint on `result = p.map(square, mylist)` and debug it, it prints 8 errors (my CPU can run 4*2=8 threads) and then hangs.

**Comment by Nitrooo** [comment] 2019-06-30 13:47
```
import os
from pathos.multiprocessing import ProcessPool


def square(n):
    print("Worker process id for {0}: {1}".format(n, os.getpid()))
    return n * n


if __name__ == "__main__":
    print(os.getpid())
    mylist = [1, 2, 3, 4, 5]
    p = ProcessPool()
    print("pool created")
    result = p.map(square, mylist)
    print(result)
```

I tested this script on a clean Windows 10 virtual machine on a clean **3.7.3** venv: same behavior (`ModuleNotFoundError: No module named 'multiprocess'`).
Same machine, same script, clean **3.7.0** venv:

```
C:\Users\User\PycharmProjects\test\venv\Scripts\python.exe C:/Users/User/PycharmProjects/test/test.py
6332
pool created
multiprocess.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "C:\Users\User\PycharmProjects\test\venv\lib\site-packages\multiprocess\pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "C:\Users\User\PycharmProjects\test\venv\lib\site-packages\multiprocess\pool.py", line 44, in mapstar
    return list(map(*args))
  File "C:\Users\User\PycharmProjects\test\venv\lib\site-packages\pathos\helpers\mp_helper.py", line 15, in <lambda>
    func = lambda args: f(*args)
  File "C:/Users/User/PycharmProjects/test/test.py", line 6, in square
    print("Worker process id for {0}: {1}".format(n, os.getpid()))
NameError: name 'os' is not defined
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:/Users/User/PycharmProjects/test/test.py", line 15, in <module>
    result = p.map(square, mylist)
  File "C:\Users\User\PycharmProjects\test\venv\lib\site-packages\pathos\multiprocessing.py", line 137, in map
    return _pool.map(star(f), zip(*args)) # chunksize
  File "C:\Users\User\PycharmProjects\test\venv\lib\site-packages\multiprocess\pool.py", line 268, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "C:\Users\User\PycharmProjects\test\venv\lib\site-packages\multiprocess\pool.py", line 657, in get
    raise self._value
NameError: name 'os' is not defined

Process finished with exit code 1
```

While this script:
```
import os
from multiprocessing.pool import Pool


def square(n):
    print("Worker process id for {0}: {1}".format(n, os.getpid()))
    return n * n


if __name__ == "__main__":
    print(os.getpid())
    mylist = [1, 2, 3, 4, 5]
    p = Pool()
    print("pool created")
    result = p.map(square, mylist)
    print(result)

```
on the same 3.7.0 venv works as expected:
```
C:\Users\User\PycharmProjects\test\venv\Scripts\python.exe C:/Users/User/PycharmProjects/test/test.py
6224
pool created
Worker process id for 1: 4948
Worker process id for 2: 4948
Worker process id for 3: 4948
Worker process id for 4: 4948
Worker process id for 5: 4948
[1, 4, 9, 16, 25]

Process finished with exit code 0
```

**Comment by mmckerns** [comment] 2019-06-30 15:31
@Nitrooo: I was able to reproduce your errors.  Here's what I did... I updated my install of `dill` to `0.3.0`... then I get the errors you see.  For the different versions of python, I had `dill` `0.2.x` installed, and it worked as expected.  So it would seem that there's something that broke on windows for a recent `dill`, not on `multiprocess`.  What version of `dill` are you using?

**Comment by Nitrooo** [comment] 2019-06-30 16:24
I had `dill-0.3.0` installed on all my venvs. On Python 3.7.0 I get `NameError: name 'os' is not defined` even on `dill-0.2.9`. On `dill-0.2.8.2`, instead, it works without errors, so it must be something introduced from `dill-0.2.9` on.

**Comment by Nitrooo** [comment] 2019-06-30 16:56
On 3.7.3 (`pathos-0.2.4`, `multiprocess-0.70.8`) I keep on getting `ModuleNotFoundError: No module named 'multiprocess'` on every `dill` version I tested against (`0.3.0`, `0.2.9`, `0.2.8.2` and `0.2.0`). It seems to be a different issue thought.
On this venv configuration :
```
(new_venv) C:\Users\User\PycharmProjects\test>pip list
Package      Version
------------ -------
dill         0.2.8.2
multiprocess 0.70.7  <--------- 
pathos       0.2.4
pip          19.0.3
pox          0.2.6
ppft         1.6.6.1
pyreadline   2.1
setuptools   40.8.0
six          1.12.0
```
I get:
```
C:\Users\User\PycharmProjects\test\new_venv\Scripts\python.exe C:/Users/User/PycharmProjects/test/test.py
3208
pool created
```
with no errors, but it hangs forever.

**Comment by mmckerns** [comment] 2019-06-30 19:10
I had venvs with `dill-0.2.x` where `x=8, 7`, and the python is `3.7.2` from conda.  None of those showed a hang or errors.  However, updating to `dill-0.3.0` does.  I get the same result, actually, for python 3.5 and 3.6, which I also tested at that time.  This will need some investigation of what changed in `multiprocess` and `dill`, and in combinations thereof.  But I'm pretty sure it has to do with how `dill` recognizes objects in the global dict.

**Comment by Nitrooo** [comment] 2019-06-30 20:16
Well, this is confusing.
Out of curiosity, I installed `Python 3.7.2` (from https://www.python.org/ftp/python/3.7.2/python-3.7.2-amd64.exe), and on the venv I get after `pip install pathos`:
```
Package      Version
------------ -------
dill         0.3.0
multiprocess 0.70.8
pathos       0.2.4
pip          19.0.3
pox          0.2.6
ppft         1.6.6.1
setuptools   40.8.0
six          1.12.0
```
and even after forcing `dill` version to `0.2.8.2`:
```
Package      Version
------------ -------
dill         0.2.8.2
multiprocess 0.70.8
pathos       0.2.4
pip          19.0.3
pox          0.2.6
ppft         1.6.6.1
pyreadline   2.1
setuptools   40.8.0
six          1.12.0
```
I get the same behavior: no errors, but it hangs after the "pool created" message.

**Comment by mmckerns** [comment] 2019-06-30 20:51
Oh, one thing I didn't mention.  On windows, you need to use `multiprocess.freeze_support()`.

**Comment by Nitrooo** [comment] 2019-06-30 21:19
Added `multiprocess.freeze_support()` right after `if __name__ == "__main__":`, but the behavior doesn't change on both `3.7.3` and `3.7.2`.

**Comment by mmckerns** [comment] 2019-09-27 20:52
related/same as https://github.com/uqfoundation/pathos/issues/65

**Comment by Mijago** [comment] 2020-02-26 10:15
I also ran into this right now. I created a new Python 3.7.6 venv and did some tests with the example code above.
Using any version prior to 0.70.8 not throw the error anymore. dill-0.2.x did not help.

It writes "pool created", creates 26 Threads (thats 3x my core count), but nothing else happens. The threads stay alive until I kill them. But this may be a different issue.

**Comment by tpike3** [comment] 2020-04-05 19:35
I am using pathos and Mesa BatchRunnerMP for a COVID model am getting the same error. How can I adjust BatchRunnerMP to prevents this error? 

For reference Mesa BathRunerMP is located:  https://github.com/projectmesa/mesa/blob/master/mesa/batchrunner.py

**Comment by mmckerns** [comment] 2020-04-07 16:53
I think that this may be related to https://github.com/uqfoundation/multiprocess/issues/65, but for Windows not Mac -- and the above linked issues for `dill` and `pathos` are other instances where this change in behavior impacts how `multiprocessing` (and thus `multiprocess`) builds and ships it's pickled objects.  The workaround I used in https://github.com/uqfoundation/multiprocess/commit/72571308a2530948ac9238ee61a3c48eba6ed17d was to change the default context from `spawn` to `fork`, which was used in earlier versions of `multiprocessing`. 

@tpike3: If you need to use windows, the workaround some people are using is to downgrade `multiprocess` or `dill`, but I expect that the issue is probably that on windows dill is having trouble accessing the global dict as noted in https://github.com/uqfoundation/dill/issues/323.  If you can edit your BatchRunnerMP class so that the variables are encapsulated (i.e. locally referenced, imported, passed in, etc) and don't rely on a lookup in the global dict, then you'll have a better chance that the code will get around this issue.

**Comment by tpike3** [comment] 2020-04-07 19:07
OK, I will work with batchrunnerMP and see if I can make the fix. I will let you know.

**Comment by tpike3** [comment] 2020-04-14 20:00
Figured out my issue. I had a lambda function inside the model reporter which was causing it to break. 

Works in pathos>=0.2.3

Easier to fix the data collection than any other action, so I will work that angle.

**Comment by mmckerns** [comment] 2020-04-26 12:22
I believe this should be fixed due to https://github.com/uqfoundation/dill/issues/363.  Reopen if that's not the case.

**Closed by mmckerns** 2020-04-26 12:22 UTC
Labels: bug
