### ISSUE TITLE
Read the docs is down. 

### ISSUE THREAD

**Issue by assolisc** [uqfoundation/multiprocess#89] opened 2021-08-10 08:07 UTC
I cannot access the read the docs page. It shows up as a page with instructions to set-up a read the docs page.

**Comment by assolisc** [comment] 2021-08-10 08:10
Installed the package through pip, I'm not a big fan of building from source unless strictly necessary,

**Comment by mmckerns** [comment] 2021-08-10 10:55
Closing as a duplicate of #39. You should not need to build from source.  The code is pure-python, unless you are on an old unsupported 2.x version of python.

**Closed by mmckerns** 2021-08-10 10:55 UTC
Labels: duplicate

**Comment by assolisc** [comment] 2021-08-10 14:43
Hi @mmckerns , no I am using python 3.9 ,3.7, and 3.6 for a couple of projects. But when I try to access the https://multiprocess.readthedocs.io/ from the web, it appears broken. Will follow your suggestion and use the multiprocessing documentation. But I'm guessing that you haven't dropped the python 2.x support that you mentioned before.
